image: node:14

stages:
  - build
  - deploy

variables:
  FORCE_COLOR: "1"

before_script:
  - node --version
  - npm --version

build:
  stage: build
  tags: [shared-ci-docker]
  before_script:
    - npm ci
    - npx gatsby info
  script:
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - public

deploy:
  stage: deploy
  tags: [shared-ci-docker]
  before_script:
    - npm i netlify-cli
  script:
    - >
      npx netlify deploy
      --prod
      --auth $NETLIFY_AUTH_TOKEN
      --site $NETLIFY_SITE_ID
      --dir public
      --message `git describe --always`
  only:
    - main
  dependencies:
    - build
